site_name: Gauge Generator
site_url: https://adan2013.github.io/Gauge-Generator/
repo_url: https://github.com/adan2013/Gauge-Generator
site_author: adan2013
theme: readthedocs
extra_css: [extra.css]
nav:
  - Home: index.md
  - Interface: interface.md
  - Layer types: layers.md
  - Examples: examples.md